### ISSUE TITLE
Add support for scribble constants in the language

### ISSUE THREAD

**Issue by cd1m0** [ConsenSys/scribble#116]
In properties we've written there is often some constant  that keeps on repeating. (e.g. number of decimals in a Ray/Wad, number of seconds in a day, etc). It would make code cleaner if we could define Scribble constants similarly to how we can define user helper functions in scribble. I.e. something like:

```solidity
/// #define SECONDS_PER_DAY: uint  = 60*60*24;
contract Foo {
    uint timestamp;
    
    /// #limit {:msg "no more than a day passed"} block.timestamp - timestamp < SECONDS_PER_DAY;
    function bar() public {}
}
```

There is still the issue here that constants would be defined per contract, while sometimes we may want to use them from another contract. No clear story for that yet, but the incremental improvement might be worth it.

**Comment by blitz-1306** [comment]
Summary from discussion with @cd1m0 (correct me if I would be wrong anywhere):
- Consider to support primitive and comparable types. We would like to have `string`s and `bytes` if possible.
- Constants would be stored either in scribble utils contract (preferrable) or in standalone generated library (less preferrable due to possible `import` implications, but still possible).
  - In case of utils contract, make sure that for any affected contract, we mark it with `ctx.needsUtils(contract.vScope);`.
  - Storing constants in single contract would require end-users to avoid name clashes. Therefore single constant name can not be used for different contract annotation scopes. This should be catched and checked as early as possible - during transpiling if possible.
- We would like to consider `SourceUnit`s documentation for declaring constants, but it would require patching **solc-typed-ast**. For not it is out of scope and we focusing on at least adding feature in minimal fashion.
