### ISSUE TITLE
Support for arbitrary assertions

### ISSUE THREAD

**Issue by wolflo** [ConsenSys/scribble#120]
There are times when an assertion is relatively simple and easiest to express in-line. This can obviously be expressed directly in solidity, but using Scribble in these cases would save the trouble of carefully removing these assertions before deploying (or incurring the gas cost of these checks in live contracts).

I am envisioning a `#raw` or `#inline` property type that allows you to write a normal solidity if statement + assertion, and just takes care of inserting/removing this assertion for you.
```solidity
contract Calculator {
    enum Op {
        PLUS,
        TIMES
    }
    function calc(Op operator, uint left, uint right) public returns (uint result) {
        if (operator == Op.TIMES) {
            return left * right;
        }
        if (operator == Op.PLUS) {
            return left + right;
        }
        /// #raw {:msg "no return"} assert (false);
    }
}
```

**Comment by wolflo** [comment]
Maybe `#if_reached` is more on brand?

**Comment by cd1m0** [comment]
Sooo we actually just added this :). Its in the develop branch of scribble, and in the next release (coming in the next few days). But right now with develop the following will work:


```
contract Calculator {
    enum Op {
        PLUS,
        TIMES
    }
    function calc(Op operator, uint left, uint right) public returns (uint result) {
        if (operator == Op.TIMES) {
            return left * right;
        }
        if (operator == Op.PLUS) {
            return left + right;
        }
        /// #assert {:msg "no return"} false;
        0;
    }
}
```

Note there is currently only 1 syntactic limitation: the annotation cannot be the last thing in a block. Thats why I added the dummy `0;` at the end. Otherwise you can put an annotation before any statement inside the body of a function

**Comment by wolflo** [comment]
Thank you!
