### ISSUE TITLE
Implication and calculation old value

### ISSUE THREAD

**Issue by newcodepusher** [ConsenSys/scribble#32]
I spent a lot of time figuring out what the error is in a similar situation.

```solidity
pragma solidity >=0.6.0 <0.8.0;
contract Test {
    uint public value;

    function set(uint newValue) external {
        value =  newValue;
    }

    /// if_succeeds {:msg "wrong calculation"} from != address(0) ==> old(Test(from).value()) + old(value) == value;
    function add(address from) external {
        if(from != address(0)) {
	  value =  value + Test(from).value();
	  Test(from).set(block.timestamp);
        }
    }
}
```

The scribble will generate a similar code, but the fact is that "from" can equal 0 when reading the old value.
`        _v.old_0 = Test(from).value();`

Can you take into account the condition when saving the old value?
Or tell me how to write something like this in a shorter way, there may be more than one old values

`/// if_succeeds {:msg "wrong calculation"} from != address(0) ==> old(from != address(0) ? Test(from).value() : 0) + old(value) == value;`

**Comment by cd1m0** [comment]
Its difficult to take the condition `from != address(0)` into account, since it refers to the value **after** the original function was called, and its difficult to say for an arbitrary computation if it remains constant during the computation of the function. Even if its easy for this particular case, we need to take into account a useful set of use cases.

If the condition was written `old(from != address(0))` its obvious syntactically that its safe to take it into account when computing `old` values on the RHS of the implication. Doing this cleanly is tricky though. We could do a simple syntactic match for `old(e) => e1` and put all the `old(e')` from `e1` behind Ifs. However then we might miss cases when the user expressed the same implication in a different way (e.g. `!(old(e)) || e1`).

Implementing the latter would take a bit, as we need to think through all the edge cases. Regarding writing it shorter, unfortunately I can't think of anything much shorter than what you did. 

If you have to type the same expression many times, perhaps you can define it as a "user function". We just added those. It would look like this:

```
/// define getOldValue(address from) uint = from != address(0) ? Test(from).value() : 0;
contract Test {
....

    /// if_succeeds {:msg "wrong calculation"} from != address(0) ==> getOldValue(from) + old(value) == value;
    function add(address from) external {
}
```

Hope this helps

**Comment by newcodepusher** [comment]
if there is no other option "user function" might be an acceptable solution, thanks for the answer

**Comment by cd1m0** [comment]
Closing this issue for now. If you feel that there is still something else actionable for us to do, please feel free to re-open.
