### ISSUE TITLE
Accessors are not properly supported

### ISSUE THREAD

**Issue by axic** [ConsenSys/scribble#72]
```solidity
contract A {
  uint public a;
}

contract B {
  function f() external returns (uint) {
     return A(msg.sender).a();
  }
}
```

The above code will crash on `develop`:
```
/scribble/dist/util/misc.js:16
    throw new Error(message);
    ^

Error: Unexpected callee variable without function type
    at Object.assert (/scribble/dist/util/misc.js:16:11)
    at getAssignments (/scribble/dist/instrumenter/state_vars.js:182:21)
    at getAssignments.next (<anonymous>)
    at Object.findAliasedStateVars (/scribble/dist/instrumenter/state_vars.js:266:21)
    at new InstrumentationContext (/scribble/dist/instrumenter/instrumentation_context.js:231:38)
    at Object.<anonymous> (/scribble/dist/bin/scribble.js:471:26)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```

**Comment by axic** [comment]
@cd1m0 found you a new issue 😉

**Comment by cd1m0** [comment]
Doing good work if you're finding issues ;). Thanks dude! Will look into it shortly (need to work on this cool new tool that @blitz-1306 started. Will open-source soon)

**Comment by axic** [comment]
This works now with bded274, no more "crashes". No I can play with the actual Scribble statements and see what I find 😅

**Comment by cd1m0** [comment]
So I accidentally pushed a partial fix for this in development. However looking at it there is another small problem with that code. The issue comes from [this](https://github.com/ConsenSys/scribble/blob/develop/src/instrumenter/state_vars.ts#L256) case of `getAssignments`:

```
            } else if (decl instanceof VariableDeclaration) {
                // For variable definitions we have 2 cases - either its a public state var or a function pointer variable
                if (decl.stateVariable) {
                    // This case is tricky, as there are no formal parameters in the AST to yield. (the getter is implicitly generated)
                    // Luckily, these implicit assignments don't allow aliasing (as they are external calls).
                    // Furthermore these use sites don't need special instrumentation.
                    // So we allow imprecision here and skip these
                    continue;
                } else {
                    assert(
                        decl.vType instanceof FunctionTypeName,
                        "Unexpected callee variable without function type"
                    );

                    formals = decl.vType.vParameterTypes.vParameters;
                }
```

`getAssignments` is a poor-man's replacement for a dataflow analysis (which is a little tricky to do for an AST instead of a proper IR). The goal is to detect all AST sites where explicit or implicit assignments may happen, in order to both detect aliasing (which prevents certain instrumentations) as well as detect all sites that need to be re-written for state variable annoations and `forall` mapping annotations. 

When we have a callsite of the type:
```
    someFunVar = ...
    someFunVar(arg1);
```

There is implicit assignments from `arg1`to the formal parameters of all possible functions that `someFunVar` may be assigned. A simpler over-approximation of this would be an implicit assignment from `arg1` to the formal parameters of all declared functions that have the same type as `someFunVar`. Instead we just return an assignment from `arg1` to the formal parameter in `someFunVar`'s type. This is incorrect from the point of view of dataflow, but I think its sufficient for the limited cases that scribble has for `getAssignments`.

Just making a note of this somewhere before I forget :)
